function m(b,a,c,d){b.o.kb(b.pb,a,c,d)}function n(b,a,c,d){b.o.da?m(b,a,c,d):b.o.Ne()._OnMessageFromDOM({type:"event",component:b.pb,handler:a,dispatchOpts:d||null,data:c,responseId:null})}function aa(b,a,c){b.o.B(b.pb,a,c)}function q(b,a){for(const [c,d]of a)aa(b,c,d)}function v(b){b.Tb||(b.o.xc(b.de),b.Tb=!0)}window.Hb=class{constructor(b,a){this.o=b;this.pb=a;this.Tb=!1;this.de=()=>this.Na()}hd(){}Na(){}};
window.Af=class{constructor(){this.dd=-1}j(){-1!==this.dd&&(self.clearTimeout(this.dd),this.dd=-1)}};"use strict";function ba(b,a){aa(b,"get-element",c=>{const d=w(b,c.elementId);return a(d,c)})}function w(b,a){b=b.Sa.get(a);if(!b)throw Error(`no element with id ${a}`);return b.Rb}
window.md=class extends self.Hb{constructor(b,a){super(b,a);this.Sa=new Map;this.nb=!0;q(this,[["create",()=>{throw Error("required override");}],["destroy",c=>{c=c.elementId;const d=w(this,c);this.nb&&d.parentElement.removeChild(d);this.Sa.delete(c)}],["set-visible",c=>{if(this.nb){var d=this.Sa.get(c.elementId),e=d.Rb;d.Nd?e.style.display=c.isVisible?"":"none":d.ff=!!c.isVisible}}],["update-position",c=>{if(this.nb){var d=this.Sa.get(c.elementId),e=d.Rb,f=this.o;e.style.left=c.left+"px";e.style.top=
c.top+"px";e.style.width=c.width+"px";e.style.height=c.height+"px";var g=c.fontSize;null!==g&&(e.style.fontSize=g+"em");g=c.htmlIndex;d.lf=g;g=f.od(g);g!==d.Ea&&(e.remove(),f.qc(g).appendChild(e),d.Ea=g,f.Gc());c=c.htmlZIndex;c!==d.Oc&&(d.Oc=c,f.Gc());d.Nd||(d.Nd=!0,d.ff&&(e.style.display=""))}}],["update-state",c=>{w(this,c.elementId);throw Error("required override");}],["focus",c=>{const d=w(this,c.elementId);c.focus?d.focus():d.blur()}],["set-css-style",c=>{const d=w(this,c.elementId),e=c.prop;
c=c.val;e.startsWith("--")?d.style.setProperty(e,c):d.style[e]=c}],["set-attribute",c=>{w(this,c.elementId).setAttribute(c.name,c.val)}],["remove-attribute",c=>{w(this,c.elementId).removeAttribute(c.name)}]]);ba(this,c=>c)}};"use strict";const ca=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),x=/android/i.test(navigator.userAgent);let da=0;
function y(b){const a=document.createElement("script");a.async=!1;a.type="module";return b.qf?new Promise(c=>{const d="c3_resolve_"+da;++da;self[d]=c;a.textContent=b.uf+`\n\nself["${d}"]();`;document.head.appendChild(a)}):new Promise((c,d)=>{a.onload=c;a.onerror=d;a.src=b;document.head.appendChild(a)})}
async function ea(){if(!navigator.userActivation||"undefined"===typeof OffscreenCanvas)return!1;try{let b=!1;const a=new Worker(URL.createObjectURL(new Blob(['\n\tself.addEventListener("message", () =>\n\t{\n\t\ttry {\n\t\t\tconst offscreenCanvas = new OffscreenCanvas(32, 32);\n\t\t\tconst gl = offscreenCanvas.getContext("webgl");\n\t\t\tself.postMessage(!!gl);\n\t\t}\n\t\tcatch (err)\n\t\t{\n\t\t\tconsole.warn("Feature detection worker error:", err);\n\t\t\tself.postMessage(false);\n\t\t}\n\t});'],{type:"text/javascript"})),
{get type(){b=!0}}),c=await new Promise(d=>{a.addEventListener("message",e=>{a.terminate();d(e.data)});a.postMessage("")});return b&&c}catch(b){return console.warn("Error feature detecting worker mode: ",b),!1}}let z=new Audio;
const fa={"audio/webm; codecs=opus":!!z.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!z.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!z.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!z.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!z.canPlayType("audio/mp4"),"audio/mpeg":!!z.canPlayType("audio/mpeg")};z=null;async function ha(b){b=await ia(b);return(new TextDecoder("utf-8")).decode(b)}
function ia(b){return new Promise((a,c)=>{const d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsArrayBuffer(b)})}const B=[];let D=0;window.RealFile=window.File;const E=[],F=new Map,G=new Map;let ja=0;const ka=[];self.runOnStartup=function(b){if("function"!==typeof b)throw Error("runOnStartup called without a function");ka.push(b)};const na=new Set(["cordova","playable-ad","instant-games"]);let oa=!1;
window.Kb=class b{constructor(a){this.da=a.wf;this.wa=null;this.aa="";this.$a=a.tf;this.Fb={};this.Ua=this.ta=null;this.Ra=[];this.ma=null;this.Rd=!0;this.M=[];this.Yc=[];this.Zc=!1;this.ee=()=>this.Le();this.Qc=!1;this.Kd=0;this.ub=null;this.Za=-1;this.kf=()=>this.We();this.Cb=new Set;this.ed=null;this.fe=[];this.A=a.ge;this.Ub="file"===location.protocol.substr(0,4);if("playable-ad"===this.A||"instant-games"===this.A)this.da=!1;if("cordova"===this.A&&this.da&&x){const c=/Chrome\/(\d+)/i.exec(navigator.userAgent);
c&&90<=parseInt(c[1],10)||(this.da=!1)}this.La()?self.chrome.webview.addEventListener("message",c=>this.zd(c.data)):"macos-wkwebview"===this.A&&(self.C3WrapperOnMessage=c=>this.zd(c));this.Xb=this.qa=null;"html5"!==this.A||window.isSecureContext||console.warn("[Construct] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.B("canvas","update-size",c=>this.$e(c));this.B("canvas","set-html-layer-count",
c=>this._OnSetHTMLLayerCount(c));this.B("canvas","cleanup-html-layers",()=>this.Re());this.B("runtime","cordova-fetch-local-file",c=>this.Se(c));this.B("runtime","create-job-worker",()=>this.Te());this.B("runtime","send-wrapper-extension-message",c=>this.Ze(c));"cordova"===this.A?document.addEventListener("deviceready",()=>this.xd(a)):this.xd(a)}j(){this.yc();this.wa&&(this.wa=this.wa.onmessage=null);this.ta&&(this.ta.terminate(),this.ta=null);this.Ua&&(this.Ua.j(),this.Ua=null);for(const {canvas:a,
cb:c}of this.M)a.remove(),c.remove();this.M.length=0}pd(){return this.M[0].canvas}od(a){return Math.min(a,this.M.length-1)}qc(a){if(0>a||a>=this.M.length)throw new RangeError("invalid canvas layer");return this.M[a].cb}Be(){return ca&&"cordova"===this.A}ib(){const a=navigator.userAgent;return ca&&na.has(this.A)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(a)}ze(){return x}qd(){return x&&na.has(this.A)}sd(){return"windows-webview2"===this.A||!!("preview"===this.A&&window.chrome&&window.chrome.webview&&
window.chrome.webview.postMessage)}La(){return this.sd()||"xbox-uwp-webview2"===this.A}async xd(a){this.da&&!await ea()&&(this.da=!1);"macos-wkwebview"===this.A?this.lb({type:"ready"}):this.La()&&(this.bf(),this.fe=(await this.Qe()).registeredComponentIds);if("playable-ad"===this.A){this.qa=self.c3_base64files;this.Xb={};await this.Ie();for(let d=0,e=a.bb.length;d<e;++d){var c=a.bb[d];this.Xb.hasOwnProperty(c)?a.bb[d]={qf:!0,uf:this.Xb[c]}:this.qa.hasOwnProperty(c)&&(a.bb[d]=URL.createObjectURL(this.qa[c]))}a.lc=
[]}if("nwjs"===this.A&&self.nw&&self.nw.App.manifest["c3-steam-mode"]){let d=0;this.xc(()=>{d++;document.body.style.opacity=0===d%2?"1":"0.999"})}a.sf?this.aa=a.sf:(c=location.origin,this.aa=("null"===c?"file:///":c)+location.pathname,c=this.aa.lastIndexOf("/"),-1!==c&&(this.aa=this.aa.substr(0,c+1)));a.yf&&(this.Fb=a.yf);c=new MessageChannel;this.wa=c.port1;this.wa.onmessage=d=>this._OnMessageFromRuntime(d.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(d=>this.Ve(d));this.ub=
new self.Ce(this);await pa(this.ub);"object"===typeof window.StatusBar&&window.StatusBar.hide();if("object"===typeof window.AndroidFullScreen)try{await new Promise((d,e)=>{window.AndroidFullScreen.immersiveMode(d,e)})}catch(d){console.error("Failed to enter Android immersive mode: ",d)}this.da?await this.Pe(a,c.port2):await this.Oe(a,c.port2)}Ac(a){a=this.Fb.hasOwnProperty(a)?this.Fb[a]:a.endsWith("/workermain.js")&&this.Fb.hasOwnProperty("workermain.js")?this.Fb["workermain.js"]:"playable-ad"===
this.A&&this.qa.hasOwnProperty(a)?this.qa[a]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async oc(a,c,d){if(a.startsWith("blob:"))return new Worker(a,d);if("cordova"===this.A&&this.Ub)return a=await this.Gb(d.pf?a:this.$a+a),new Worker(URL.createObjectURL(new Blob([a],{type:"application/javascript"})),d);a=new URL(a,c);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),d)}return new Worker(a,
d)}oa(){return Math.max(window.innerWidth,1)}ga(){return Math.max(window.innerHeight,1)}wd(a){var c=this.aa,d=location.href,e=this.oa(),f=this.ga(),g=window.devicePixelRatio,h=b.hb(),k=a.Df,l=window.cr_previewImageBlobs||this.qa,p=window.cr_previewProjectFileBlobs,r=window.cr_previewProjectFiles,t=window.cr_swClientId||"";a=a.ge;var u=(new URLSearchParams(self.location.search)).has("debug"),A=this.ub;return{runtimeBaseUrl:c,previewUrl:d,windowInnerWidth:e,windowInnerHeight:f,devicePixelRatio:g,isFullscreen:h,
projectData:k,previewImageBlobs:l,previewProjectFileBlobs:p,previewProjectFileSWUrls:r,swClientId:t,exportType:a,isDebug:u,ife:!!self.Cf,jobScheduler:{inputPort:A.Pc,outputPort:A.Xc,maxNumWorkers:A.gf},supportedAudioFormats:fa,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.$a+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.$a+"opus.wasm.wasm",isFileProtocol:this.Ub,isiOSCordova:this.Be(),isiOSWebView:this.ib(),isWindowsWebView2:this.sd(),isAnyWebView2Wrapper:this.La(),wrapperComponentIds:this.fe,
isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async Pe(a,c){const d=this.Ac(a.xf);"preview"===this.A?(this.ta=new Worker("previewworker.js",{type:"module",name:"Runtime"}),await new Promise((l,p)=>{const r=t=>{this.ta.removeEventListener("message",r);t.data&&"ok"===t.data.type?l():p()};this.ta.addEventListener("message",r);this.ta.postMessage({type:"construct-worker-init","import":(new URL(d,this.aa)).toString()})})):this.ta=await this.oc(d,this.aa,{type:"module",name:"Runtime",pf:!0});
const e=document.createElement("canvas");e.style.display="none";const f=e.transferControlToOffscreen();document.body.appendChild(e);const g=document.createElement("div");g.className="c3htmlwrap";document.body.appendChild(g);this.M.push({canvas:e,cb:g});window.c3canvas=e;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();let h=a.lc||[],k=a.bb;h=await Promise.all(h.map(l=>this.Oa(l)));k=await Promise.all(k.map(l=>this.Oa(l)));if("cordova"===this.A)for(let l=0,p=a.kc.length;l<p;++l){const r=
a.kc[l],t=r[0];if(t===a.fd||"scriptsInEvents.js"===t||t.endsWith("/scriptsInEvents.js"))r[1]=await this.Oa(t)}this.ta.postMessage(Object.assign(this.wd(a),{type:"init-runtime",isInWorker:!0,messagePort:c,canvas:f,workerDependencyScripts:h,engineScripts:k,projectScripts:a.kc,mainProjectScript:a.fd,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[c,f,...qa(this.ub)]);this.Ra=E.map(l=>new l(this));this.vd();H(e);ra(g);sa(this.ma);self.c3_callFunction=(l,p)=>{var r=this.ma;return r.o.td(r.pb,"js-invoke-function",
{name:l,params:p})};"preview"===this.A&&(self.goToLastErrorScript=()=>this.kb("runtime","go-to-last-error-script"))}async Oe(a,c){const d=document.createElement("canvas");d.style.display="none";document.body.appendChild(d);var e=document.createElement("div");e.className="c3htmlwrap";document.body.appendChild(e);this.M.push({canvas:d,cb:e});window.c3canvas=d;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();this.Ra=E.map(h=>new h(this));this.vd();H(d);ra(e);e=a.bb.map(h=>"string"===
typeof h?(new URL(h,this.aa)).toString():h);if(Array.isArray(a.lc)){var f=[...a.lc].map(h=>h instanceof Blob?URL.createObjectURL(h):h);e.unshift(...f)}e=await Promise.all(e.map(h=>this.Oa(h)));await Promise.all(e.map(h=>y(h)));e=self.C3_ProjectScriptsStatus;f=a.fd;const g=a.kc;for(let [h,k]of g)if(k||(k=h),h===f)try{k=await this.Oa(k),await y(k),"preview"!==this.A||e[h]||this.Bd(h,"main script did not run to completion")}catch(l){this.Bd(h,l)}else if("scriptsInEvents.js"===h||h.endsWith("/scriptsInEvents.js"))k=
await this.Oa(k),await y(k);"preview"===this.A&&"object"!==typeof self.zf.Bf?(this.Nb(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this.wd(a),{isInWorker:!1,messagePort:c,canvas:d,runOnStartupFunctions:ka}),sa(this.ma),this.yd(),this.Ua=self.C3_CreateRuntime(a),await self.C3_InitRuntime(this.Ua,
a))}Bd(a,c){this.Nb();console.error(`[Preview] Failed to load project main script (${a}): `,c);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}yd(){this.Nb()}Nb(){const a=window.cr_previewLoadingElem;a&&(a.parentElement.removeChild(a),window.cr_previewLoadingElem=null)}async Te(){const a=await ta(this.ub);return{outputPort:a,transferables:[a]}}$e(a){if(!this.Qc){var c=a.styleWidth+"px",d=a.styleHeight+
"px",e=a.marginLeft+"px",f=a.marginTop+"px";for(const {canvas:g,cb:h}of this.M)g.style.width=c,g.style.height=d,g.style.marginLeft=e,g.style.marginTop=f,h.style.width=c,h.style.height=d,h.style.marginLeft=e,h.style.marginTop=f,this.Rd&&(g.style.display="",h.style.display="");document.documentElement.style.setProperty("--construct-scale",a.displayScale);this.Rd=!1}}_OnSetHTMLLayerCount(a){var c=a.count,d=a.immediate,e=a.styleWidth+"px",f=a.styleHeight+"px";const g=a.marginLeft+"px",h=a.marginTop+"px";
a=[];const k=[];if(c<this.M.length)for(;this.M.length>c;){const {canvas:l,cb:p}=this.M.pop();p.remove();this.da&&!d?this.Yc.push(l):l.remove()}else if(c>this.M.length)for(let l=0,p=c-this.M.length;l<p;++l)c=document.createElement("canvas"),c.classList.add("c3overlay"),this.da?(d=c.transferControlToOffscreen(),a.push(d),k.push(d)):a.push(c),document.body.appendChild(c),d=document.createElement("div"),d.classList.add("c3htmlwrap","c3overlay"),document.body.appendChild(d),c.style.width=e,c.style.height=
f,c.style.marginLeft=g,c.style.marginTop=h,d.style.width=e,d.style.height=f,d.style.marginLeft=g,d.style.marginTop=h,H(c),ra(d),this.M.push({canvas:c,cb:d});for(const l of this.Ra)if(l instanceof window.md&&l.nb)for(const p of l.Sa.values())e=l.o.od(p.lf),f=p.Ea,-1!==e&&-1!==f&&e!==f&&(f=p.Rb,f.remove(),l.o.qc(e).appendChild(f),p.Ea=e);this.Gc();return{addedCanvases:a,transferables:k}}Re(){for(const a of this.Yc)a.remove();this.Yc.length=0}Gc(){this.Zc||(this.Zc=!0,this.xc(this.ee))}Le(){this.Ad(this.ee);
this.Zc=!1;let a=[];for(var c of this.Ra)if(c instanceof window.md){var d=c.nb?[...c.Sa.values()]:null;d&&a.push(...d)}a.sort((g,h)=>{const k=g.Ea,l=h.Ea;return k!==l?k-l:g.Oc-h.Oc});let e=d=c=0,f=a.length;for(;e<f;++e){const g=a[e];g.Ea!==c&&(this.ud(c,a.slice(d,e)),c=g.Ea,d=e)}d<e&&this.ud(c,a.slice(d,e))}ud(a,c){if(!(1>=c.length||a>=this.M.length)){c=c.map(k=>k.Rb);var d=new Set(c);a=this.qc(a);for(var e=Array.from(a.children).filter(k=>d.has(k)),f=0,g=Math.min(c.length,e.length);f<g&&c[f]===e[f];++f);
for(var h=f;h<g;++h)e[h].remove();for(h=f;h<g;++h)a.appendChild(c[h])}}Ne(){if(this.da)throw Error("not available in worker mode");return this.Ua}kb(a,c,d,e,f){this.wa.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:null},f)}td(a,c,d,e,f){const g=ja++,h=new Promise((k,l)=>{G.set(g,{resolve:k,reject:l})});this.wa.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:g},f);return h}_OnMessageFromRuntime(a){const c=a.type;if("event"===
c)return this.Ue(a);if("result"===c)this.Xe(a);else if("runtime-ready"===c)this.Ye();else if("alert-error"===c)this.Nb(),alert(a.message);else if("creating-runtime"===c)this.yd();else throw Error(`unknown message '${c}'`);}Ue(a){const c=a.component,d=a.handler,e=a.data,f=a.responseId;if(a=F.get(c))if(a=a.get(d)){var g=null;try{g=a(e)}catch(h){console.error(`Exception in '${c}' handler '${d}':`,h);null!==f&&this.Mb(f,!1,""+h);return}if(null===f)return g;g&&g.then?g.then(h=>this.Mb(f,!0,h)).catch(h=>
{console.error(`Rejection from '${c}' handler '${d}':`,h);this.Mb(f,!1,""+h)}):this.Mb(f,!0,g)}else console.warn(`[DOM] No handler '${d}' for component '${c}'`);else console.warn(`[DOM] No event handlers for component '${c}'`)}Mb(a,c,d){let e;d&&d.transferables&&(e=d.transferables);this.wa.postMessage({type:"result",responseId:a,isOk:c,result:d},e)}Xe(a){const c=a.responseId,d=a.isOk;a=a.result;const e=G.get(c);d?e.resolve(a):e.reject(a);G.delete(c)}B(a,c,d){let e=F.get(a);e||(e=new Map,F.set(a,e));
if(e.has(c))throw Error(`[DOM] Component '${a}' already has handler '${c}'`);e.set(c,d)}static mc(a){if(E.includes(a))throw Error("DOM handler already added");E.push(a)}vd(){for(const a of this.Ra)if("runtime"===a.pb){this.ma=a;return}throw Error("cannot find runtime DOM handler");}Ve(a){this.kb("debugger","message",a)}Ye(){for(const a of this.Ra)a.hd()}static hb(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||oa)}static Cd(a){oa=!!a}xc(a){this.Cb.add(a);
this.Fc()}Ad(a){this.Cb.delete(a);0===this.Cb.size&&this.yc()}Fc(){-1===this.Za&&0<this.Cb.size&&(this.Za=requestAnimationFrame(this.kf))}yc(){-1!==this.Za&&(cancelAnimationFrame(this.Za),this.Za=-1)}We(){this.Za=-1;for(const a of this.Cb)a();this.Fc()}Ca(a){this.ma.Ca(a)}Ma(a){this.ma.Ma(a)}Ec(){this.ma.Ec()}Lb(a){this.ma.Lb(a)}Ae(){return!!fa["audio/webm; codecs=opus"]}async cf(a){a=await this.td("runtime","opus-decode",{arrayBuffer:a},null,[a]);return new Float32Array(a)}Ee(a){this.Qc=!0;this.Kd=
a}ye(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}rd(a){return!this.ye(a)}async Oa(a){return"cordova"===this.A&&(a.startsWith("file:")||this.Ub&&this.rd(a))?(a.startsWith(this.aa)&&(a=a.substr(this.aa.length)),a=await this.Gb(a),URL.createObjectURL(new Blob([a],{type:"application/javascript"}))):a}async Se(a){const c=a.filename;switch(a.as){case "text":return await this.xe(c);case "buffer":return await this.Gb(c);default:throw Error("unsupported type");
}}ld(a){const c=window.cordova.file.applicationDirectory+"www/"+a;return new Promise((d,e)=>{window.resolveLocalFileSystemURL(c,f=>{f.file(d,e)},e)})}async xe(a){a=await this.ld(a);return await ha(a)}zc(){if(B.length&&!(8<=D)){D++;var a=B.shift();this.Je(a.filename,a.vf,a.nf)}}Gb(a){return new Promise((c,d)=>{B.push({filename:a,vf:e=>{D--;this.zc();c(e)},nf:e=>{D--;this.zc();d(e)}});this.zc()})}async Je(a,c,d){try{const e=await this.ld(a),f=await ia(e);c(f)}catch(e){d(e)}}zd(a){if("entered-fullscreen"===
a)b.Cd(!0),I(this.ma);else if("exited-fullscreen"===a)b.Cd(!1),I(this.ma);else if("object"===typeof a){const c=a.type;"wrapper-init-response"===c?(this.ed(a),this.ed=null):"extension-message"===c?this.kb("runtime","wrapper-extension-message",a):console.warn("Unknown wrapper message: ",a)}else console.warn("Unknown wrapper message: ",a)}Ze(a){this.lb({type:"extension-message",componentId:a.componentId,messageId:a.messageId,params:a.params||[],asyncId:a.asyncId})}lb(a){this.La()?window.chrome.webview.postMessage(JSON.stringify(a)):
"macos-wkwebview"===this.A&&window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a))}bf(){window.moveTo=(a,c)=>{this.lb({type:"set-window-position",windowX:Math.ceil(a),windowY:Math.ceil(c)})};window.resizeTo=(a,c)=>{this.lb({type:"set-window-size",windowWidth:Math.ceil(a),windowHeight:Math.ceil(c)})}}Qe(){return this.La()?new Promise(a=>{this.ed=a;this.lb({type:"wrapper-init"})}):Promise.resolve()}async Ie(){const a=[];for(const [c,d]of Object.entries(this.qa))a.push(this.He(c,d));
await Promise.all(a)}async He(a,c){if("object"===typeof c)this.qa[a]=new Blob([c.str],{type:c.type}),this.Xb[a]=c.str;else{let d=await this.Me(c);d||(d=this.Ke(c));this.qa[a]=d}}async Me(a){try{return await (await fetch(a)).blob()}catch(c){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",c),null}}Ke(a){a=this.af(a);return this.Ge(a.data,
a.rf)}af(a){var c=a.indexOf(",");if(0>c)throw new URIError("expected comma in data: uri");var d=a.substring(c+1);c=a.substring(5,c).split(";");a=c[0]||"";const e=c[2];d="base64"===c[1]||"base64"===e?atob(d):decodeURIComponent(d);return{rf:a,data:d}}Ge(a,c){var d=a.length;let e=d>>2,f=new Uint8Array(d),g=new Uint32Array(f.buffer,0,e),h,k;for(k=h=0;h<e;++h)g[h]=a.charCodeAt(k++)|a.charCodeAt(k++)<<8|a.charCodeAt(k++)<<16|a.charCodeAt(k++)<<24;for(d&=3;d--;)f[k]=a.charCodeAt(k),++k;return new Blob([f],
{type:c})}};"use strict";const J=self.Kb,ua=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),K={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},va={dispatchUserScriptEvent:!0},wa={dispatchRuntimeEvent:!0};function xa(b){return new Promise((a,c)=>{const d=document.createElement("link");d.onload=()=>a(d);d.onerror=e=>c(e);d.rel="stylesheet";d.href=b;document.head.appendChild(d)})}function ya(b){return new Promise((a,c)=>{const d=new Image;d.onload=()=>a(d);d.onerror=e=>c(e);d.src=b})}
async function L(b){b=URL.createObjectURL(b);try{return await ya(b)}finally{URL.revokeObjectURL(b)}}function za(b){return new Promise((a,c)=>{let d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsText(b)})}
async function Aa(b,a,c){if(!/firefox/i.test(navigator.userAgent))return await L(b);var d=await za(b);d=(new DOMParser).parseFromString(d,"image/svg+xml");const e=d.documentElement;if(e.hasAttribute("width")&&e.hasAttribute("height")){const f=e.getAttribute("width"),g=e.getAttribute("height");if(!f.includes("%")&&!g.includes("%"))return await L(b)}e.setAttribute("width",a+"px");e.setAttribute("height",c+"px");d=(new XMLSerializer).serializeToString(d);b=new Blob([d],{type:"image/svg+xml"});return await L(b)}
function Ba(b){do{if(b.parentNode&&b.hasAttribute("contenteditable"))return!0;b=b.parentNode}while(b);return!1}const Ca=new Set(["input","textarea","datalist","select"]),Da=new Set(["canvas","body","html"]);function M(b){b.target.tagName&&Da.has(b.target.tagName.toLowerCase())&&b.preventDefault()}function Ea(b){b.target.tagName&&b.target.classList.contains("c3htmlwrap")&&b.preventDefault()}function Fa(b){(b.metaKey||b.ctrlKey)&&b.preventDefault()}
self.C3_GetSvgImageSize=async function(b){b=await L(b);if(0<b.width&&0<b.height)return[b.width,b.height];b.style.position="absolute";b.style.left="0px";b.style.top="0px";b.style.visibility="hidden";document.body.appendChild(b);const a=b.getBoundingClientRect();document.body.removeChild(b);return[a.width,a.height]};self.C3_RasterSvgImageBlob=async function(b,a,c,d,e){b=await Aa(b,a,c);const f=document.createElement("canvas");f.width=d;f.height=e;f.getContext("2d").drawImage(b,0,0,a,c);return f};
let Ga=!1;document.addEventListener("pause",()=>Ga=!0);document.addEventListener("resume",()=>Ga=!1);function H(b){b.addEventListener("selectstart",M);b.addEventListener("gesturehold",M);b.addEventListener("pointerdown",M)}function ra(b){b.addEventListener("selectstart",Ea);b.addEventListener("gesturehold",Ea);b.addEventListener("touchstart",Ea)}function sa(b){b.Jd=!0;b.Tc=b.o.oa();b.vb=b.o.ga()}
function I(b){if(!b.ka){var a=J.hb();a&&"any"!==b.bd&&Ha(b);m(b,"fullscreenchange",{isFullscreen:a,innerWidth:b.oa(),innerHeight:b.ga()})}}async function Ia(b){await Promise.all(b.webfonts.map(async a=>{a=new FontFace(a.name,`url('${a.url}')`);document.fonts.add(a);await a.load()}))}
async function Ja(b){var a=b.imageBitmapOpts;b=await self.C3_RasterSvgImageBlob(b.blob,b.imageWidth,b.imageHeight,b.surfaceWidth,b.surfaceHeight);a=a?await createImageBitmap(b,a):await createImageBitmap(b);return{imageBitmap:a,transferables:[a]}}async function Ka(b){return await self.C3_GetSvgImageSize(b.blob)}function La(b){window.c3_postToMessagePort&&(b.from="runtime",window.c3_postToMessagePort(b))}
function Ma(b){self.setTimeout(()=>{b.Id=!0},1E3);"cordova"===b.o.A?(document.addEventListener("pause",()=>Na(b,!0)),document.addEventListener("resume",()=>Na(b,!1))):document.addEventListener("visibilitychange",()=>Na(b,"hidden"===document.visibilityState));b.ac=!("hidden"!==document.visibilityState&&!Ga);return{isSuspended:b.ac}}
function Oa(b){b.Ed||(b.Ed=!0,window.addEventListener("deviceorientation",a=>{b.ka||m(b,"deviceorientation",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp,webkitCompassHeading:a.webkitCompassHeading,webkitCompassAccuracy:a.webkitCompassAccuracy},K)}),window.addEventListener("deviceorientationabsolute",a=>{b.ka||m(b,"deviceorientationabsolute",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},K)}))}
function Pa(b){b.Dd||(b.Dd=!0,window.addEventListener("devicemotion",a=>{if(!b.ka){var c=null,d=a.acceleration;d&&(c={x:d.x||0,y:d.y||0,z:d.z||0});d=null;var e=a.accelerationIncludingGravity;e&&(d={x:e.x||0,y:e.y||0,z:e.z||0});e=null;var f=a.rotationRate;f&&(e={alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0});m(b,"devicemotion",{acceleration:c,accelerationIncludingGravity:d,rotationRate:e,interval:a.interval,timeStamp:a.timeStamp},K)}}))}async function Qa(b){await xa(b.url)}
function Ra(b,a){b.Ld=a.message;-1===b.Kc&&(b.Kc=setTimeout(()=>{b.Kc=-1;const c=document.getElementById("exportToVideoMessage");c&&(c.textContent=b.Ld)},250))}function Sa(b,a){console.warn("[Construct] Fullscreen request failed: ",a);m(b,"fullscreenerror",{isFullscreen:J.hb(),innerWidth:b.oa(),innerHeight:b.ga()})}
function Na(b,a){b.ac!==a&&((b.ac=a)?b.o.yc():b.o.Fc(),m(b,"visibilitychange",{hidden:a}),!a&&b.o.ib()&&(b=()=>{document.scrollingElement.scrollTop=0;document.scrollingElement.scrollLeft=0},setTimeout(b,50),setTimeout(b,100),setTimeout(b,250),setTimeout(b,500)))}
function Ta(b,a,c){"Backspace"===c.key&&M(c);if(b.o.La()){var d=["r","p","f","g","u"];(["F3","F5","F7"].includes(c.key)||c.ctrlKey&&d.includes(c.key))&&c.preventDefault()}b.ka||(d=ua.get(c.code)||c.code,n(b,a,{code:d,key:c.key,which:c.which,repeat:c.repeat,altKey:c.altKey,ctrlKey:c.ctrlKey,metaKey:c.metaKey,shiftKey:c.shiftKey,timeStamp:c.timeStamp},K))}
function N(b,a,c,d){b.ka||c.sourceCapabilities&&c.sourceCapabilities.firesTouchEvents||c.originalEvent&&c.originalEvent.sourceCapabilities&&c.originalEvent.sourceCapabilities.firesTouchEvents||n(b,a,{button:c.button,buttons:c.buttons,clientX:c.clientX,clientY:c.clientY+b.za,pageX:c.pageX,pageY:c.pageY+b.za,movementX:c.movementX||0,movementY:c.movementY||0,timeStamp:c.timeStamp},d)}
function O(b,a,c){if(!b.ka){var d=0;"mouse"===c.pointerType&&(d=b.Vc);n(b,a,{pointerId:c.pointerId,pointerType:c.pointerType,button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.za,pageX:c.pageX,pageY:c.pageY+b.za,movementX:c.movementX||0,movementY:c.movementY||0,width:c.width||0,height:c.height||0,pressure:c.pressure||0,tangentialPressure:c.tangentialPressure||0,tiltX:c.tiltX||0,tiltY:c.tiltY||0,twist:c.twist||0,timeStamp:c.timeStamp},K);"mouse"===c.pointerType&&
(b.Vc=c.buttons)}}function Ua(b,a,c){document.body.style.position="";document.body.style.overflow="";document.body.style.transform="";b.za=0;if(0<c){var d=document.activeElement;d&&(d=d.getBoundingClientRect(),a=(d.top+d.bottom)/2-(a-c)/2,a>c&&(a=c),0>a&&(a=0),0<a&&(document.body.style.position="absolute",document.body.style.overflow="visible",document.body.style.transform=`translateY(${-a}px)`,b.za=a))}}
function Va(b,a,c,d){const e=b.oa(),f=b.ga();b.ab=-1;e!=a||f!=c?m(b,"window-resize",{innerWidth:e,innerHeight:f,devicePixelRatio:window.devicePixelRatio,isFullscreen:J.hb()}):10>d&&Wa(b,e,f,d+1)}function Wa(b,a,c,d){-1!==b.ab&&clearTimeout(b.ab);b.ab=setTimeout(()=>Va(b,a,c,d),48)}
function Ha(b){b=b.bd;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}function Xa(b){return!b||b===document||b===window||b===document.body||"canvas"===b.tagName.toLowerCase()}
J.mc(class extends self.Hb{constructor(b){super(b,"runtime");this.Jd=!1;this.ab=-1;this.bd="any";this.ac=this.Dd=this.Ed=!1;this.hc=document.createElement("div");this.hc.className="c3-screen-reader-text";this.hc.setAttribute("aria-live","polite");document.body.appendChild(this.hc);this.Ga=null;this.ka=!1;this.Ld="";this.Kc=-1;this.Id=!1;this.Tc=b.oa();this.vb=b.ga();this.za=this.Eb=0;b.B("runtime","invoke-download",c=>{const d=c.url;c=c.filename;const e=document.createElement("a"),f=document.body;
e.textContent=c;e.href=d;e.download=c;f.appendChild(e);e.click();f.removeChild(e)});b.B("runtime","load-webfonts",c=>Ia(c));b.B("runtime","raster-svg-image",c=>Ja(c));b.B("runtime","get-svg-image-size",c=>Ka(c));b.B("runtime","set-target-orientation",c=>{this.bd=c.targetOrientation});b.B("runtime","register-sw",()=>{window.C3_RegisterSW&&window.C3_RegisterSW()});b.B("runtime","post-to-debugger",c=>La(c));b.B("runtime","go-to-script",c=>La(c));b.B("runtime","before-start-ticking",()=>Ma(this));b.B("runtime",
"debug-highlight",c=>{if(c.show){this.Ga||(this.Ga=document.createElement("div"),this.Ga.id="inspectOutline",document.body.appendChild(this.Ga));var d=this.Ga;d.style.display="";d.style.left=c.left-1+"px";d.style.top=c.top-1+"px";d.style.width=c.width+2+"px";d.style.height=c.height+2+"px";d.textContent=c.name}else this.Ga&&(this.Ga.style.display="none")});b.B("runtime","enable-device-orientation",()=>Oa(this));b.B("runtime","enable-device-motion",()=>Pa(this));b.B("runtime","add-stylesheet",c=>Qa(c));
b.B("runtime","script-create-worker",c=>{const d=c.port2;(new Worker(c.url,c.opts)).postMessage({type:"construct-worker-init",port2:d},[d])});b.B("runtime","alert",c=>{alert(c.message)});b.B("runtime","screen-reader-text",c=>{var d=c.type;"create"===d?(d=document.createElement("p"),d.id="c3-sr-"+c.id,d.textContent=c.text,this.hc.appendChild(d)):"update"===d?(d=document.getElementById("c3-sr-"+c.id))?d.textContent=c.text:console.warn(`[Construct] Missing screen reader text with id ${c.id}`):"release"===
d?(d=document.getElementById("c3-sr-"+c.id))?d.remove():console.warn(`[Construct] Missing screen reader text with id ${c.id}`):console.warn(`[Construct] Unknown screen reader text update '${d}'`)});b.B("runtime","hide-cordova-splash",()=>{navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()});b.B("runtime","set-exporting-to-video",c=>{this.ka=!0;const d=document.createElement("h1");d.id="exportToVideoMessage";d.textContent=c.message;document.body.prepend(d);document.body.classList.add("exportingToVideo");
this.o.pd().style.display="";this.o.Ee(c.duration)});b.B("runtime","export-to-video-progress",c=>Ra(this,c));b.B("runtime","exported-to-video",c=>{window.mf({type:"exported-video",arrayBuffer:c.arrayBuffer,contentType:c.contentType,time:c.time})});b.B("runtime","exported-to-image-sequence",c=>{window.mf({type:"exported-image-sequence",blobArr:c.blobArr,time:c.time,gif:c.gif})});const a=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",c=>{const d=c.target;a.has(d.tagName.toLowerCase())||
Ba(d)||c.preventDefault()});window.addEventListener("selectstart",M);window.addEventListener("gesturehold",M);window.addEventListener("touchstart",M,{passive:!1});window.addEventListener("pointerdown",M,{passive:!1});this.Vc=0;window.addEventListener("mousedown",c=>{1===c.button&&c.preventDefault()});window.addEventListener("mousewheel",Fa,{passive:!1});window.addEventListener("wheel",Fa,{passive:!1});window.addEventListener("resize",()=>{a:{if(!this.ka&&this.Jd){var c=this.oa();var d=this.ga();if(this.o.qd()){if(this.Id){if(this.Tc===
c&&d<this.vb){this.Eb=this.vb-d;Ua(this,this.vb,this.Eb);c=void 0;break a}0<this.Eb&&(this.Eb=0,Ua(this,d,this.Eb))}this.Tc=c;this.vb=d}m(this,"window-resize",{innerWidth:c,innerHeight:d,devicePixelRatio:window.devicePixelRatio,isFullscreen:J.hb()});this.o.ib()&&(-1!==this.ab&&clearTimeout(this.ab),Va(this,c,d,0))}c=void 0}return c});window.addEventListener("fullscreenchange",()=>I(this));window.addEventListener("webkitfullscreenchange",()=>I(this));window.addEventListener("mozfullscreenchange",()=>
I(this));window.addEventListener("fullscreenerror",c=>Sa(this,c));window.addEventListener("webkitfullscreenerror",c=>Sa(this,c));window.addEventListener("mozfullscreenerror",c=>Sa(this,c));if(b.ib()){if(window.visualViewport){let c=Infinity;window.visualViewport.addEventListener("resize",()=>{const d=window.visualViewport.height;d>c&&(document.scrollingElement.scrollTop=0,document.scrollingElement.scrollLeft=0);c=d})}else window.addEventListener("focusout",()=>{{const e=document.activeElement;if(e){var c=
e.tagName.toLowerCase();var d=new Set("email number password search tel text url".split(" "));c="textarea"===c?!0:"input"===c?d.has(e.type.toLowerCase()||"text"):Ba(e)}else c=!1}c||(document.scrollingElement.scrollTop=0)});document.documentElement.setAttribute("ioswebview","")}this.Va=new Set;this.Zb=new WeakSet;this.va=!1}hd(){window.addEventListener("focus",()=>{m(this,"window-focus",null,wa)});window.addEventListener("blur",()=>{try{var a=window.parent&&window.parent.document.hasFocus()}catch(c){a=
!1}m(this,"window-blur",{parentHasFocus:a},wa);this.Vc=0});window.addEventListener("focusin",a=>{a=a.target;(Ca.has(a.tagName.toLowerCase())||Ba(a))&&m(this,"keyboard-blur",null,wa)});window.addEventListener("keydown",a=>Ta(this,"keydown",a));window.addEventListener("keyup",a=>Ta(this,"keyup",a));window.addEventListener("mousedown",a=>N(this,"mousedown",a,va));window.addEventListener("mousemove",a=>N(this,"mousemove",a,va));window.addEventListener("mouseup",a=>N(this,"mouseup",a,va));window.addEventListener("dblclick",
a=>N(this,"dblclick",a,K));window.addEventListener("wheel",a=>{this.ka||m(this,"wheel",{clientX:a.clientX,clientY:a.clientY+this.za,pageX:a.pageX,pageY:a.pageY+this.za,deltaX:a.deltaX,deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},K)});window.addEventListener("pointerdown",a=>{window!==window.top&&window.focus();Xa(a.target)&&document.activeElement&&!Xa(document.activeElement)&&document.activeElement.blur();O(this,"pointerdown",a)});this.o.da&&"undefined"!==typeof window.onpointerrawupdate&&
self===self.top?window.addEventListener("pointerrawupdate",a=>{O(this,"pointermove",a)}):window.addEventListener("pointermove",a=>O(this,"pointermove",a));window.addEventListener("pointerup",a=>O(this,"pointerup",a));window.addEventListener("pointercancel",a=>O(this,"pointercancel",a));const b=()=>this.Ec();window.addEventListener("pointerup",b,!0);window.addEventListener("touchend",b,!0);window.addEventListener("click",b,!0);window.addEventListener("keydown",b,!0);window.addEventListener("gamepadconnected",
b,!0);this.o.ze()&&!this.o.qd()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{Ua(this,this.ga(),navigator.virtualKeyboard.boundingRect.height)}));this.o.ib()&&(document.scrollingElement.scrollTop=0,document.scrollingElement.scrollLeft=0)}oa(){return this.o.oa()}ga(){return this.o.ga()}Ec(){var b=[...this.Va];this.Va.clear();if(!this.va)for(const a of b)(b=a.play())&&b.catch(()=>{this.Zb.has(a)||this.Va.add(a)})}Ca(b){if("function"!==
typeof b.play)throw Error("missing play function");this.Zb.delete(b);let a;try{a=b.play()}catch(c){this.Va.add(b);return}a&&a.catch(()=>{this.Zb.has(b)||this.Va.add(b)})}Ma(b){this.Va.delete(b);this.Zb.add(b)}Lb(b){this.va=!!b}});"use strict";
async function pa(b){if(b.df)throw Error("already initialised");b.df=!0;var a=b.xa.Ac(("playable-ad"===b.xa.A?b.xa.$a:"")+"dispatchworker.js");b.Jc=await b.xa.oc(a,b.ob,{name:"DispatchWorker"});a=new MessageChannel;b.Pc=a.port1;b.Jc.postMessage({type:"_init","in-port":a.port2},[a.port2]);b.Xc=await ta(b)}function qa(b){return[b.Pc,b.Xc]}
async function ta(b){const a=b.Sd.length;var c=b.xa.Ac(("playable-ad"===b.xa.A?b.xa.$a:"")+"jobworker.js");c=await b.xa.oc(c,b.ob,{name:"JobWorker"+a});const d=new MessageChannel,e=new MessageChannel;b.Jc.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);c.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":e.port2},[d.port2,e.port2]);b.Sd.push(c);return e.port1}
self.Ce=class{constructor(b){this.xa=b;this.ob=b.aa;this.ob="preview"===b.A?this.ob+"workers/":this.ob+b.$a;this.gf=Math.min(navigator.hardwareConcurrency||2,16);this.Jc=null;this.Sd=[];this.Xc=this.Pc=null}};"use strict";window.C3_Is_Supported&&(window.c3_runtimeInterface=new self.Kb({wf:!0,xf:"workermain.js",bb:["scripts/c3runtime.js"],kc:[],fd:"",tf:"scripts/",lc:[],ge:"html5"}));"use strict";
self.Kb.mc(class extends self.Hb{constructor(b){super(b,"mouse");q(this,[["cursor",a=>{document.documentElement.style.cursor=a}],["request-pointer-lock",()=>{this.o.pd().requestPointerLock()}],["release-pointer-lock",()=>{document.exitPointerLock()}]]);document.addEventListener("pointerlockchange",()=>{m(this,"pointer-lock-change",{"has-pointer-lock":!!document.pointerLockElement})});document.addEventListener("pointerlockerror",()=>{m(this,"pointer-lock-error",{"has-pointer-lock":!!document.pointerLockElement})})}});
"use strict";const Ya=180/Math.PI;
async function Za(b,a){if(a.isiOSCordova||a.isSafari)b.cc=!0;b.cd=a.timeScaleMode;b.Xd=["equalpower","HRTF","soundfield"][a.panningModel];b.Hd=["linear","inverse","exponential"][a.distanceModel];b.Yd=a.refDistance;b.Wd=a.maxDistance;b.$d=a.rolloffFactor;if(b.o.Qc)b.cc=!0,b.g=new OfflineAudioContext({numberOfChannels:2,sampleRate:48E3,length:Math.ceil(48E3*b.o.Kd)});else{var c={latencyHint:a.latencyHint};b.ce||(c.sampleRate=48E3);if("undefined"!==typeof AudioContext)b.g=new AudioContext(c);else if("undefined"!==
typeof webkitAudioContext)b.g=new webkitAudioContext(c);else throw Error("Web Audio API not supported");$a(b);b.g.onstatechange=()=>{"running"!==b.g.state&&$a(b);m(b,"audiocontext-state",{audioContextState:b.g.state})}}b.Qa=b.g.createGain();b.Qa.connect(b.g.destination);c=a.listenerPos;b.$[0]=c[0];b.$[1]=c[1];b.$[2]=c[2];b.g.listener.setPosition(c[0],c[1],c[2]);b.g.listener.setOrientation(...b.ba);self.C3_GetAudioContextCurrentTime=()=>b.g.currentTime;try{await Promise.all(a.preloadList.map(d=>P(b,
d.originalUrl,d.url,d.type,!1)))}catch(d){console.error("[Construct] Preloading sounds failed: ",d)}return{sampleRate:b.g.sampleRate,audioContextState:b.g.state,outputLatency:b.g.outputLatency||0}}
async function ab(b,a){var c=a.originalUrl,d=a.url;const e=a.type,f=a.isMusic,g=a.tags,h=a.isLooping,k=a.vol,l=a.pos,p=a.panning,r=a.stereoPan;let t=a.off;0<t&&!a.trueClock&&(b.g.getOutputTimestamp?(a=b.g.getOutputTimestamp(),t=t-a.performanceTime/1E3+a.contextTime):t=t-performance.now()/1E3+b.g.currentTime);b.Td=g.slice(0);bb(b,g);try{b.R=await cb(b,c,d,e,g,f);if(p){Q(b.R,!0);var u=b.R,A=p.innerAngle,la=p.outerAngle,ma=p.outerGain;if(u.tb){db(u,p.x,p.y,p.z,p.angle);var C=self.eb.Fe;u.ra[0]!==C(A)&&
(u.ra[0]=C(A),u.F.coneInnerAngle=C(A));u.ra[1]!==C(la)&&(u.ra[1]=C(la),u.F.coneOuterAngle=C(la));u.ra[2]!==ma&&(u.ra[2]=ma,u.F.coneOuterGain=ma)}p.hasOwnProperty("uid")&&(b.R.pa=p.uid)}else"number"===typeof r&&0!==r?(R(b.R,!0),fb(b.R,r)):(Q(b.R,!1),R(b.R,!1));b.R.Play(h,k,l,t)}catch(rb){console.error("[Construct] Audio: error starting playback: ",rb);return}finally{c=g.join(" ");d=b.Bb.get(c);if(!d)throw Error("expected pending tag");d.gd--;0===d.gd&&(d.resolve(),b.Bb.delete(c))}v(b)}
async function gb(b,a){var c=a.tags;const d=a.vol,e=a.duration;a=a.stopOnEnd;await hb(b,c);for(const h of S(b,c))if(!h.ua){c=h.G.gain;c.cancelScheduledValues(0);var f=h.u.g.currentTime,g=f+e;c.setValueAtTime(c.value,f);c.linearRampToValueAtTime(d,g);h.Ja=d;h.Ta=g;h.be=a}T(b)}async function ib(b,a){const c=a.tags;a=a.rate;await hb(b,c);for(const d of S(b,c))d.la!==a&&(d.la=a,d.Da())}async function jb(b,a){const c=a.tags;a=a.pos;await hb(b,c);for(const d of S(b,c))d.uc(a)}
async function kb(b,a){const c=a.originalUrl,d=a.url,e=a.type;a=a.isMusic;try{await cb(b,c,d,e,"",a)}catch(f){console.error("[Construct] Audio: error preloading: ",f)}}async function lb(b,a){if(a=await P(b,"",a.url,a.type,a.isMusic,!0))a.j(),a=b.ia.indexOf(a),-1!==a&&b.ia.splice(a,1)}
async function mb(b,a){const c=a.type;var d=a.hasOwnProperty("tags")?a.tags:[a.tag];const e=a.params;let f;if("convolution"===c)try{f=await P(b,a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(k){console.log("[Construct] Audio: error loading convolution: ",k);return}for(const k of d){if("filter"===c)d=new self.me(b,...e);else if("delay"===c)d=new self.ke(b,...e);else if("convolution"===c){var g=d=new self.je(b,f.ha,...e),h=a.bufferType;g.Fd=a.bufferOriginalUrl;g.Gd=h}else if("flanger"===c)d=
new self.ne(b,...e);else if("phaser"===c)d=new self.pe(b,...e);else if("gain"===c)d=new self.oe(b,...e);else if("stereopan"===c)d=new self.re(b,...e);else if("tremolo"===c)d=new self.se(b,...e);else if("ringmod"===c)d=new self.qe(b,...e);else if("distortion"===c)d=new self.le(b,...e);else if("compressor"===c)d=new self.ie(b,...e);else if("analyser"===c)d=new self.he(b,...e);else throw Error("invalid effect type");g=b;h=k;h=h.toLowerCase();let l=g.ja.get(h);l||(l=[],g.ja.set(h,l));d.Qd=l.length;d.ad=
h;l.push(d);nb(g,h)}ob(b)}
async function pb(b,a){const c=a.saveLoadMode;if(3!==c){var d=[];for(var e of b.H)e.Aa()&&1===c||!e.Aa()&&2===c?d.push(e):e.j();b.H=d}for(const f of b.ja.values())for(const g of f)g.j();b.ja.clear();b.ic=a.timeScale;b.Lc=a.gameTime;d=a.listenerPos;b.$[0]=d[0];b.$[1]=d[1];b.$[2]=d[2];b.g.listener.setPosition(d[0],d[1],d[2]);d=a.listenerOrientation;if(Array.isArray(d)){for(e=0;6>e;++e)b.ba[e]=d[e];b.g.listener.setOrientation(...b.ba)}b.va=a.isSilent;b.o.Lb(b.va);b.Yb=a.masterVolume;b.Qa.gain.value=
b.Yb;d=[];for(const f of Object.values(a.effects))d.push(Promise.all(f.map(g=>mb(b,g))));await Promise.all(d);await Promise.all(a.playing.map(f=>qb(b,f,c)));T(b)}
async function sb(b,a){try{const c=b.g.suspend(a.time);b.Pd?b.g.resume():(b.g.startRendering().then(d=>{const e=[];for(let f=0,g=d.numberOfChannels;f<g;++f){const h=d.getChannelData(f);e.push(h.buffer)}b.o.kb("runtime","offline-audio-render-completed",{duration:d.duration,length:d.length,numberOfChannels:d.numberOfChannels,sampleRate:d.sampleRate,channelData:e},null,e)}).catch(d=>tb(d)),b.Pd=!0);await c}catch(c){tb(c)}}
function $a(b){b.Sb||(b.Nc=!1,window.addEventListener("pointerup",b.ya,!0),window.addEventListener("touchend",b.ya,!0),window.addEventListener("click",b.ya,!0),window.addEventListener("keydown",b.ya,!0),b.Sb=!0)}
async function P(b,a,c,d,e,f){for(var g of b.ia)if(g.gb()===c)return await ub(g),g;if(f)return null;if(e&&(b.cc||b.Od)){f=0;for(let h=0,k=b.ia.length;h<k;++h)g=b.ia[h],b.ia[f]=g,g.Aa()?g.j():++f;b.ia.length=f}f="audio/webm; codecs=opus"===d&&!b.ce;e&&f&&(b.Od=!0);c=!e||b.cc||f?new self.ve(b,a,c,d,e,f):new self.te(b,a,c,d,e);b.ia.push(c);await ub(c);b.Vd.has(a)||(m(b,"buffer-metadata",{originalUrl:a,duration:c.fa()}),b.Vd.add(a));return c}
function vb(b,a){return b===a||b.normalize().toLowerCase()===a.normalize().toLowerCase()}function wb(b,a){return(a=b.ja.get(a.toLowerCase()))?a[0].N():b.ea()}function nb(b,a){a=a.toLowerCase();let c=b.ea();var d=b.ja.get(a);if(d&&d.length){c=d[0].N();for(let f=0,g=d.length;f<g;++f){var e=d[f];f+1===g?e.U(b.ea()):e.U(d[f+1].N())}}for(const f of xb(b,a))d=c,e=f.ca||f.F||f.G,e.disconnect(),e.connect(d);b.Ha&&b.Uc===a&&(b.Ha.disconnect(),b.Ha.connect(c))}
function*xb(b,a){if(a)for(const c of b.H)vb(0<c.na.length?c.na[0]:"",a)&&(yield c);else b.R&&!b.R.O()&&(yield b.R)}function yb(b,a,c){return c?b.o.cf(a).then(d=>{const e=b.g.createBuffer(1,d.length,48E3);e.getChannelData(0).set(d);return e}):new Promise((d,e)=>{b.g.decodeAudioData(a,d,e)})}function zb(b,a){let c=0;for(let d=0,e=b.H.length;d<e;++d){const f=b.H[d];b.H[c]=f;f.P===a?f.j():++c}b.H.length=c}
function*S(b,a){if(0<a.length)for(const d of b.H){a:{b=d.na;var c=a;for(const e of c){c=!1;for(const f of b)if(vb(f,e)){c=!0;break}if(!c){b=!1;break a}}b=!0}b&&(yield d)}else b.R&&!b.R.O()&&(yield b.R)}async function cb(b,a,c,d,e,f){for(const g of b.H)if(g.gb()===c&&(g.nc()||f))return g.na=e,g;a=await P(b,a,c,d,f);e="html5"===a.Hc?new self.ue(a.u,a,e):new self.we(a.u,a,e);b.H.push(e);return e}
function bb(b,a){a=a.join(" ");let c=b.Bb.get(a);if(!c){let d=null;c={gd:0,promise:new Promise(e=>d=e),resolve:d};b.Bb.set(a,c)}c.gd++}function hb(b,a){return(b=b.Bb.get((0===a.length?b.Td:a).join(" ")))?b.promise:Promise.resolve()}function T(b){if(0<b.Pa.size)v(b);else for(const a of b.H)if(!a.I&&!a.O()){v(b);break}}function Ab(b,a,c,d){m(b,"trigger",{type:a,tags:c,aiid:d})}function ob(b){b.Rc||(b.Rc=!0,Promise.resolve().then(()=>Bb(b)))}
function Bb(b){const a={};for(const [c,d]of b.ja)a[c]=d.map(e=>e.fb());m(b,"fxstate",{fxstate:a});b.Rc=!1}
async function qb(b,a,c){if(3!==c){var d=a.bufferOriginalUrl,e=a.bufferUrl,f=a.bufferType,g=a.isMusic,h=a.tags,k=a.isLooping,l=a.volume,p=a.playbackTime;if(!g||1!==c)if(g||2!==c){c=null;try{c=await cb(b,d,e,f,h,g)}catch(r){console.error("[Construct] Audio: error loading audio state: ",r);return}b=c;(d=a.pan)?(Q(b,!0),e=b.F,f=d.pos,b.Xa[0]=f[0],b.Xa[1]=f[1],b.Xa[2]=f[2],f=d.orient,b.Wa[0]=f[0],b.Wa[1]=f[1],b.Wa[2]=f[2],e.setPosition(...b.Xa),e.setOrientation(...b.Wa),b.ra[0]=d.cia,b.ra[1]=d.coa,b.ra[2]=
d.cog,e.coneInnerAngle=d.cia,e.coneOuterAngle=d.coa,e.coneOuterGain=d.cog,b.pa=d.uid):Q(b,!1);b=c;d=a.stereoPan;"number"!==typeof d?R(b,!1):(R(b,!0),fb(b,d));c.Play(k,l,p,0);a.isPlaying||c.jb();c.Cc(a)}}}function tb(b){console.error("[Audio] Offline rendering error: ",b)}
self.eb=class extends self.Hb{constructor(b){super(b,"audio");this.Qa=this.g=null;this.Sb=this.Nc=!1;this.ya=()=>{if(!this.Nc){var a=this.g;"suspended"===a.state&&a.resume&&a.resume();var c=a.createBuffer(1,220,22050),d=a.createBufferSource();d.buffer=c;d.connect(a.destination);d.start(0);"running"===a.state&&this.Sb&&(this.Nc=!0,window.removeEventListener("pointerup",this.ya,!0),window.removeEventListener("touchend",this.ya,!0),window.removeEventListener("click",this.ya,!0),window.removeEventListener("keydown",
this.ya,!0),this.Sb=!1)}};this.ia=[];this.H=[];this.R=null;this.Td=[];this.Vd=new Set;this.Ud=-1;this.Bb=new Map;this.Yb=1;this.va=!1;this.cd=0;this.ic=1;this.Lc=0;this.Xd="HRTF";this.Hd="inverse";this.Yd=600;this.Wd=1E4;this.$d=1;this.$=[0,0,0];this.ba=[0,0,-1,0,1,0];this.Od=this.cc=!1;this.ce=this.o.Ae();this.ja=new Map;this.Pa=new Set;this.Pd=this.Rc=!1;this.Uc="";this.Ha=null;self.C3Audio_OnMicrophoneStream=(a,c)=>{this.Ha&&this.Ha.disconnect();this.Uc=c.toLowerCase();this.Ha=this.g.createMediaStreamSource(a);
this.Ha.connect(wb(this,this.Uc))};this.Qb=null;self.C3Audio_GetOutputStream=()=>{this.Qb||(this.Qb=this.g.createMediaStreamDestination(),this.Qa.connect(this.Qb));return this.Qb.stream};self.C3Audio_DOMInterface=this;q(this,[["create-audio-context",a=>Za(this,a)],["play",a=>ab(this,a)],["stop",a=>{a=a.tags;for(const c of S(this,a))c.Ba()}],["stop-all",()=>{for(const a of this.H)a.Ba()}],["set-paused",a=>{const c=a.tags;a=a.paused;for(const d of S(this,c))a?d.jb():d.Jb();T(this)}],["set-volume",a=>
{const c=a.tags;a=a.vol;for(const d of S(this,c))U(d,a)}],["fade-volume",a=>gb(this,a)],["set-master-volume",a=>{this.Yb=a.vol;this.Qa.gain.value=this.Yb}],["set-muted",a=>{const c=a.tags;a=a.isMuted;for(const d of S(this,c))Cb(d,a)}],["set-silent",a=>{this.va=a.isSilent;this.o.Lb(this.va);for(const c of this.H)c.Ob()}],["set-looping",a=>{const c=a.tags;a=a.isLooping;for(const d of S(this,c))d.vc(a)}],["set-playback-rate",a=>ib(this,a)],["set-stereo-pan",a=>{const c=a.tags;a=a.p;for(const d of S(this,
c))R(d,!0),fb(d,a)}],["seek",a=>jb(this,a)],["preload",a=>kb(this,a)],["unload",a=>lb(this,a)],["unload-all",()=>{for(const a of this.ia)a.j();this.ia.length=0}],["set-suspended",a=>{a=a.isSuspended;!a&&this.g.resume&&this.g.resume();for(const c of this.H)c.wc(a);a&&this.g.suspend&&this.g.suspend()}],["add-effect",a=>mb(this,a)],["set-effect-param",a=>{var c=a.tags;const d=a.index,e=a.param,f=a.value,g=a.ramp;a=a.time;for(const h of c)c=this.ja.get(h.toLowerCase()),!c||0>d||d>=c.length||c[d].Z(e,
f,g,a);ob(this)}],["remove-effects",a=>{a=a.tags;for(const c of a){a=c.toLowerCase();const d=this.ja.get(a);if(!d||!d.length)break;for(const e of d)e.j();this.ja.delete(a);nb(this,a)}}],["tick",a=>{this.ic=a.timeScale;this.Lc=a.gameTime;this.Ud=a.tickCount;if(0!==this.cd)for(var c of this.H)c.Da();!(c=a.listenerPos)||this.$[0]===c[0]&&this.$[1]===c[1]&&this.$[2]===c[2]||(this.$[0]=c[0],this.$[1]=c[1],this.$[2]=c[2],this.g.listener.setPosition(c[0],c[1],c[2]));if((c=a.listenerOrientation)&&(this.ba[0]!==
c[0]||this.ba[1]!==c[1]||this.ba[2]!==c[2]||this.ba[3]!==c[3]||this.ba[4]!==c[4]||this.ba[5]!==c[5])){for(let d=0;6>d;++d)this.ba[d]=c[d];this.g.listener.setOrientation(...this.ba)}for(const d of a.instPans){a=d.uid;for(const e of this.H)e.pa===a&&db(e,d.x,d.y,d.z,d.angle)}}],["load-state",a=>pb(this,a)],["offline-render-audio",a=>sb(this,a)],["offline-render-finish",()=>{this.g.resume()}]])}V(){return this.g}ea(){return this.Qa}GetAudioContextExtern(){return this.V()}GetDestinationNodeExtern(){return this.ea()}Ib(){return this.va}Ca(b){this.o.Ca(b)}Ma(b){this.o.Ma(b)}Na(){for(var b of this.Pa)b.Na();
b=this.g.currentTime;for(var a of this.H)a.Na(b);a=this.H.filter(c=>!c.I&&!c.O()).map(c=>c.fb());m(this,"state",{tickCount:this.Ud,outputLatency:this.g.outputLatency||0,audioInstances:a,analysers:[...this.Pa].map(c=>({tag:c.ad,index:c.Qd,peak:c.Ya,rms:c.Zd,binCount:c.l.frequencyBinCount,freqBins:c.Md}))});0===a.length&&0===this.Pa.size&&this.Tb&&(this.o.Ad(this.de),this.Tb=!1)}static Fe(b){return b*Ya}static nd(b){return Math.max(Math.min(Math.pow(10,b/20),1),0)}static De(b){return Math.log(Math.max(Math.min(b,
1),0))/Math.log(10)*20}};self.Kb.mc(self.eb);"use strict";function ub(b){b.Wb||(b.Wb=b.Bc());return b.Wb}self.jd=class{constructor(b,a,c,d,e){this.u=b;this.jf=a;this.Ia=c;this.T=d;this.ef=e;this.Hc="";this.Wb=null}j(){this.Wb=this.u=null}Bc(){}V(){return this.u.V()}rc(){return this.jf}gb(){return this.Ia}pc(){return this.T}Aa(){return this.ef}fa(){}};"use strict";
self.te=class extends self.jd{constructor(b,a,c,d,e){super(b,a,c,d,e);this.Hc="html5";this.L=new Audio;this.L.crossOrigin="anonymous";this.L.autoplay=!1;this.L.preload="auto";this.wb=this.xb=null;this.L.addEventListener("canplaythrough",()=>!0);this.Ab=this.V().createGain();this.zb=null;this.L.addEventListener("canplay",()=>{this.xb&&(this.xb(),this.wb=this.xb=null);!this.zb&&this.L&&(this.zb=this.V().createMediaElementSource(this.L),this.zb.connect(this.Ab))});this.onended=null;this.L.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.L.addEventListener("error",f=>{console.error(`[Construct] Audio '${this.Ia}' error: `,f);this.wb&&(this.wb(f),this.wb=this.xb=null)})}j(){zb(this.u,this);this.Ab.disconnect();this.Ab=null;this.zb.disconnect();this.zb=null;this.L&&!this.L.paused&&this.L.pause();this.L=this.onended=null;super.j()}Bc(){return new Promise((b,a)=>{this.xb=b;this.wb=a;this.L.src=this.Ia})}W(){return this.L}fa(){return this.L.duration}};"use strict";
async function Db(b){if(b.Fa)return b.Fa;var a=b.u.o;if("cordova"===a.A&&a.rd(b.Ia)&&a.Ub)b.Fa=await a.Gb(b.Ia);else{a=await fetch(b.Ia);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);b.Fa=await a.arrayBuffer()}}async function Eb(b){if(b.ha)return b.ha;b.ha=await yb(b.u,b.Fa,b.hf);b.Fa=null}
self.ve=class extends self.jd{constructor(b,a,c,d,e,f){super(b,a,c,d,e);this.Hc="webaudio";this.ha=this.Fa=null;this.hf=!!f}j(){zb(this.u,this);this.ha=this.Fa=null;super.j()}async Bc(){try{await Db(this),await Eb(this)}catch(b){console.error(`[Construct] Failed to load audio '${this.Ia}': `,b)}}fa(){return this.ha?this.ha.duration:0}};"use strict";let Fb=0;
function Q(b,a){a=!!a;b.tb!==a&&(b.tb=a,b.tb?(R(b,!1),b.F||(b.F=b.V().createPanner(),b.F.panningModel=b.u.Xd,b.F.distanceModel=b.u.Hd,b.F.refDistance=b.u.Yd,b.F.maxDistance=b.u.Wd,b.F.rolloffFactor=b.u.$d),b.G.disconnect(),b.G.connect(b.F),b.F.connect(b.ea())):(b.F.disconnect(),b.G.disconnect(),b.G.connect(b.ea())))}
function R(b,a){a=!!a;b.Vb!==a&&(b.Vb=a,b.Vb?(Q(b,!1),b.ca=b.V().createStereoPanner(),b.G.disconnect(),b.G.connect(b.ca),b.ca.connect(b.ea())):(b.ca.disconnect(),b.ca=null,b.G.disconnect(),b.G.connect(b.ea())))}function fb(b,a){b.Vb&&b.$c!==a&&(b.ca.pan.value=a,b.$c=a)}function U(b,a){b.Ja=a;b.G.gain.cancelScheduledValues(0);b.Ta=-1;b.G.gain.value=b.sc()}function Cb(b,a){a=!!a;b.ua!==a&&(b.ua=a,b.Ob())}
function db(b,a,c,d,e){if(b.tb){var f=b.Xa,g=b.Wa,h=Math.cos(e);e=Math.sin(e);if(f[0]!==a||f[1]!==c||f[2]!==d)f[0]=a,f[1]=c,f[2]=d,b.F.setPosition(...f);if(g[0]!==h||g[1]!==e||0!==g[2])g[0]=h,g[1]=e,g[2]=0,b.F.setOrientation(...g)}}function V(b){return b.Sc?b.u.Lc:performance.now()/1E3}
self.kd=class{constructor(b,a,c){this.u=b;this.P=a;this.na=c;this.Pb=Fb++;this.G=this.V().createGain();this.G.connect(this.ea());this.F=null;this.tb=!1;this.Xa=[0,0,0];this.Wa=[0,0,0];this.ra=[0,0,0];this.ca=null;this.Vb=!1;this.$c=0;this.I=!0;this.Y=this.sa=this.J=!1;this.Ja=1;this.ua=!1;this.la=1;b=this.u.cd;this.Sc=1===b&&!this.Aa()||2===b;this.Ta=this.pa=-1;this.be=!1}j(){this.P=this.u=null;this.F&&(this.F.disconnect(),this.F=null);this.ca&&(this.ca.disconnect(),this.ca=null);this.G.disconnect();
this.G=null}V(){return this.u.V()}ea(){return wb(this.u,0<this.na.length?this.na[0]:"")}rc(){return this.P.rc()}gb(){return this.P.gb()}pc(){return this.P.pc()}Aa(){return this.P.Aa()}O(){}nc(){}IsPlaying(){return!this.I&&!this.J&&!this.O()}Ka(){}fa(){return this.P.fa()}Play(){}Ba(){}jb(){}Jb(){}Na(b){-1!==this.Ta&&b>=this.Ta&&(this.Ta=-1,this.be&&this.Ba(),Ab(this.u,"fade-ended",this.na,this.Pb))}sc(){const b=this.Ja;return isFinite(b)?b:0}Ib(){return this.u.Ib()}Ob(){}vc(){}Da(){}uc(){}wc(){}tc(){}fb(){var b=
this.Pb,a=this.na,c=this.fa(),d=-1===this.Ta?this.Ja:this.G.gain.value,e=this.IsPlaying();if(this.F){var f=this.F;f={pos:this.Xa,orient:this.Wa,cia:f.coneInnerAngle,coa:f.coneOuterAngle,cog:f.coneOuterGain,uid:this.pa}}else f=null;return{aiid:b,tags:a,duration:c,volume:d,isPlaying:e,playbackTime:this.Ka(),playbackRate:this.la,uid:this.pa,bufferOriginalUrl:this.rc(),bufferUrl:"",bufferType:this.pc(),isMusic:this.Aa(),isLooping:this.Y,isMuted:this.ua,resumePosition:this.tc(),pan:f,stereoPan:this.ca?
this.$c:null}}Cc(b){var a=b.playbackRate;this.la!==a&&(this.la=a,this.Da());Cb(this,b.isMuted)}};"use strict";
self.ue=class extends self.kd{constructor(b,a,c){super(b,a,c);this.P.Ab.connect(this.G);this.P.onended=()=>this.Dc()}j(){this.Ba();this.P.Ab.disconnect();super.j()}W(){return this.P.W()}Dc(){this.I=!0;this.pa=-1;Ab(this.u,"ended",this.na,this.Pb)}O(){return this.W().ended}nc(){return this.I?!0:this.O()}Ka(){let b=this.W().currentTime;this.Y||(b=Math.min(b,this.fa()));return b}Play(b,a,c){const d=this.W();1!==d.playbackRate&&(d.playbackRate=1);d.loop!==b&&(d.loop=b);U(this,a);this.ua=!1;d.muted&&(d.muted=
!1);if(d.currentTime!==c)try{d.currentTime=c}catch(e){console.warn(`[Construct] Exception seeking audio '${this.P.gb()}' to position '${c}': `,e)}this.u.Ca(d);this.J=this.I=!1;this.Y=b;this.la=1}Ba(){const b=this.W();b.paused||b.pause();this.u.Ma(b);this.I=!0;this.J=!1;this.pa=-1}jb(){if(!(this.J||this.I||this.O())){var b=this.W();b.paused||b.pause();this.u.Ma(b);this.J=!0}}Jb(){!this.J||this.I||this.O()||(this.u.Ca(this.W()),this.J=!1)}Ob(){this.W().muted=this.ua||this.Ib()}vc(b){b=!!b;this.Y!==
b&&(this.Y=b,this.W().loop=b)}Da(){let b=this.la;this.Sc&&(b*=this.u.ic);try{this.W().playbackRate=b}catch(a){console.warn(`[Construct] Unable to set playback rate '${b}':`,a)}}uc(b){if(!this.I&&!this.O())try{this.W().currentTime=b}catch(a){console.warn(`[Construct] Error seeking audio to '${b}': `,a)}}tc(){return this.Ka()}wc(b){b?this.IsPlaying()?(this.W().pause(),this.sa=!0):this.sa=!1:this.sa&&(this.u.Ca(this.W()),this.sa=!1)}};"use strict";
function W(b){b.s&&(b.s.onended=null,b.s.disconnect(),b.s.buffer=null);b.s=null;b.mb=null}
self.we=class extends self.kd{constructor(b,a,c){super(b,a,c);this.s=null;this.$b=d=>this.Dc(d);this.Mc=!0;this.mb=null;this.S=this.bc=this.dc=0;this.Wc=1}j(){this.Ba();W(this);this.$b=null;super.j()}Dc(b){this.J||this.sa||b.target!==this.mb||(this.I=this.Mc=!0,this.pa=-1,W(this),Ab(this.u,"ended",this.na,this.Pb))}O(){return!this.I&&this.s&&this.s.loop||this.J?!1:this.Mc}nc(){return!this.s||this.I?!0:this.O()}Ka(){let b;b=this.J?this.S:this.bc+(V(this)-this.dc)*this.la;this.Y||(b=Math.min(b,this.fa()));
return b}Play(b,a,c,d){this.ua=!1;this.Wc=1;U(this,a);W(this);this.s=this.V().createBufferSource();this.s.buffer=this.P.ha;this.s.connect(this.G);this.mb=this.s;this.s.onended=this.$b;this.s.loop=b;this.s.start(d,c);this.J=this.I=this.Mc=!1;this.Y=b;this.la=1;this.dc=V(this);this.bc=c}Ba(){if(this.s)try{this.s.stop(0)}catch(b){}this.I=!0;this.J=!1;this.pa=-1}jb(){this.J||this.I||this.O()||(this.S=this.Ka(),this.Y&&(this.S%=this.fa()),this.J=!0,this.s.stop(0))}Jb(){!this.J||this.I||this.O()||(W(this),
this.s=this.V().createBufferSource(),this.s.buffer=this.P.ha,this.s.connect(this.G),this.mb=this.s,this.s.onended=this.$b,this.s.loop=this.Y,U(this,this.Ja),this.Da(),this.s.start(0,this.S),this.dc=V(this),this.bc=this.S,this.J=!1)}sc(){return super.sc()*this.Wc}Ob(){this.Wc=this.ua||this.Ib()?0:1;U(this,this.Ja)}vc(b){b=!!b;this.Y!==b&&(this.Y=b,this.s&&(this.s.loop=b))}Da(){let b=this.la;this.Sc&&(b*=this.u.ic);this.s&&(this.s.playbackRate.value=b)}uc(b){this.I||this.O()||(this.J?this.S=b:(this.jb(),
this.S=b,this.Jb()))}tc(){return this.S}wc(b){b?this.IsPlaying()?(this.sa=!0,this.S=this.Ka(),this.Y&&(this.S%=this.fa()),this.s.stop(0)):this.sa=!1:this.sa&&(W(this),this.s=this.V().createBufferSource(),this.s.buffer=this.P.ha,this.s.connect(this.G),this.mb=this.s,this.s.onended=this.$b,this.s.loop=this.Y,U(this,this.Ja),this.Da(),this.s.start(0,this.S),this.dc=V(this),this.bc=this.S,this.sa=!1)}Cc(b){super.Cc(b);this.S=b.resumePosition}};"use strict";function X(b){return b.g.createGain()}
function Y(b,a,c,d,e){a.cancelScheduledValues(0);if(0===e)a.value=c;else switch(b=b.g.currentTime,e+=b,d){case 0:a.setValueAtTime(c,e);break;case 1:a.setValueAtTime(a.value,b);a.linearRampToValueAtTime(c,e);break;case 2:a.setValueAtTime(a.value,b),a.exponentialRampToValueAtTime(c,e)}}class Z{constructor(b){this.u=b;this.g=b.V();this.Qd=-1;this.T=this.ad="";this.m=null}j(){this.g=null}N(){}U(){}fb(){return{type:this.T,tag:this.ad,params:this.m}}}
self.me=class extends Z{constructor(b,a,c,d,e,f,g){super(b);this.T="filter";this.m=[a,c,d,e,f,g];this.v=X(this);this.i=X(this);this.i.gain.value=g;this.h=X(this);this.h.gain.value=1-g;this.D=this.g.createBiquadFilter();this.D.type=a;this.D.frequency.value=c;this.D.detune.value=d;this.D.Q.value=e;this.D.gain.vlaue=f;this.v.connect(this.D);this.v.connect(this.h);this.D.connect(this.i)}j(){this.v.disconnect();this.D.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[5]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 1:this.m[1]=a;Y(this,this.D.frequency,a,c,d);break;case 2:this.m[2]=a;Y(this,this.D.detune,a,c,d);break;case 3:this.m[3]=a;Y(this,this.D.Q,a,c,d);break;case 4:this.m[4]=a,Y(this,this.D.gain,a,c,d)}}};
self.ke=class extends Z{constructor(b,a,c,d){super(b);this.T="delay";this.m=[a,c,d];this.v=X(this);this.i=X(this);this.i.gain.value=d;this.h=X(this);this.h.gain.value=1-d;this.yb=X(this);this.X=this.g.createDelay(a);this.X.delayTime.value=a;this.rb=X(this);this.rb.gain.value=c;this.v.connect(this.yb);this.v.connect(this.h);this.yb.connect(this.i);this.yb.connect(this.X);this.X.connect(this.rb);this.rb.connect(this.yb)}j(){this.v.disconnect();this.i.disconnect();this.h.disconnect();this.yb.disconnect();
this.X.disconnect();this.rb.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,a,c,d){const e=self.eb.nd;switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[2]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 4:this.m[1]=e(a);Y(this,this.rb.gain,e(a),c,d);break;case 5:this.m[0]=a,Y(this,this.X.delayTime,a,c,d)}}};
self.je=class extends Z{constructor(b,a,c,d){super(b);this.T="convolution";this.m=[c,d];this.Gd=this.Fd="";this.v=X(this);this.i=X(this);this.i.gain.value=d;this.h=X(this);this.h.gain.value=1-d;this.qb=this.g.createConvolver();this.qb.normalize=c;this.qb.buffer=a;this.v.connect(this.qb);this.v.connect(this.h);this.qb.connect(this.i)}j(){this.v.disconnect();this.qb.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,
a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.m[1]=a,Y(this,this.i.gain,a,c,d),Y(this,this.h.gain,1-a,c,d)}}fb(){const b=super.fb();b.bufferOriginalUrl=this.Fd;b.bufferUrl="";b.bufferType=this.Gd;return b}};
self.ne=class extends Z{constructor(b,a,c,d,e,f){super(b);this.T="flanger";this.m=[a,c,d,e,f];this.v=X(this);this.h=X(this);this.h.gain.value=1-f/2;this.i=X(this);this.i.gain.value=f/2;this.sb=X(this);this.sb.gain.value=e;this.X=this.g.createDelay(a+c);this.X.delayTime.value=a;this.C=this.g.createOscillator();this.C.frequency.value=d;this.K=X(this);this.K.gain.value=c;this.v.connect(this.X);this.v.connect(this.h);this.X.connect(this.i);this.X.connect(this.sb);this.sb.connect(this.X);this.C.connect(this.K);
this.K.connect(this.X.delayTime);this.C.start(0)}j(){this.C.stop(0);this.v.disconnect();this.X.disconnect();this.C.disconnect();this.K.disconnect();this.h.disconnect();this.i.disconnect();this.sb.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[4]=a;Y(this,this.i.gain,a/2,c,d);Y(this,this.h.gain,1-a/2,c,d);break;case 6:this.m[1]=a/1E3;Y(this,this.K.gain,a/1E3,
c,d);break;case 7:this.m[2]=a;Y(this,this.C.frequency,a,c,d);break;case 8:this.m[3]=a/100,Y(this,this.sb.gain,a/100,c,d)}}};
self.pe=class extends Z{constructor(b,a,c,d,e,f,g){super(b);this.T="phaser";this.m=[a,c,d,e,f,g];this.v=X(this);this.h=X(this);this.h.gain.value=1-g/2;this.i=X(this);this.i.gain.value=g/2;this.D=this.g.createBiquadFilter();this.D.type="allpass";this.D.frequency.value=a;this.D.detune.value=c;this.D.Q.value=d;this.C=this.g.createOscillator();this.C.frequency.value=f;this.K=X(this);this.K.gain.value=e;this.v.connect(this.D);this.v.connect(this.h);this.D.connect(this.i);this.C.connect(this.K);this.K.connect(this.D.frequency);
this.C.start(0)}j(){this.C.stop(0);this.v.disconnect();this.D.disconnect();this.C.disconnect();this.K.disconnect();this.h.disconnect();this.i.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[5]=a;Y(this,this.i.gain,a/2,c,d);Y(this,this.h.gain,1-a/2,c,d);break;case 1:this.m[0]=a;Y(this,this.D.frequency,a,c,d);break;case 2:this.m[1]=a;Y(this,this.D.detune,a,c,d);
break;case 3:this.m[2]=a;Y(this,this.D.Q,a,c,d);break;case 6:this.m[3]=a;Y(this,this.K.gain,a,c,d);break;case 7:this.m[4]=a,Y(this,this.C.frequency,a,c,d)}}};self.oe=class extends Z{constructor(b,a){super(b);this.T="gain";this.m=[a];this.l=X(this);this.l.gain.value=a}j(){this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(b,a,c,d){const e=self.eb.nd;switch(b){case 4:this.m[0]=e(a),Y(this,this.l.gain,e(a),c,d)}}};
self.re=class extends Z{constructor(b,a){super(b);this.T="stereopan";this.m=[a];this.l=this.g.createStereoPanner();this.l.pan.value=a}j(){this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(b,a,c,d){a=Math.min(Math.max(a/100,-1),1);switch(b){case 9:this.m[0]=a,Y(this,this.l.pan,a,c,d)}}};
self.se=class extends Z{constructor(b,a,c){super(b);this.T="tremolo";this.m=[a,c];this.l=X(this);this.l.gain.value=1-c/2;this.C=this.g.createOscillator();this.C.frequency.value=a;this.K=X(this);this.K.gain.value=c/2;this.C.connect(this.K);this.K.connect(this.l.gain);this.C.start(0)}j(){this.C.stop(0);this.C.disconnect();this.K.disconnect();this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[1]=
a;Y(this,this.l.gain,1-a/2,c,d);Y(this,this.K.gain,a/2,c,d);break;case 7:this.m[0]=a,Y(this,this.C.frequency,a,c,d)}}};
self.qe=class extends Z{constructor(b,a,c){super(b);this.T="ringmod";this.m=[a,c];this.v=X(this);this.i=X(this);this.i.gain.value=c;this.h=X(this);this.h.gain.value=1-c;this.Db=X(this);this.Db.gain.value=0;this.C=this.g.createOscillator();this.C.frequency.value=a;this.C.connect(this.Db.gain);this.C.start(0);this.v.connect(this.Db);this.v.connect(this.h);this.Db.connect(this.i)}j(){this.C.stop(0);this.C.disconnect();this.Db.disconnect();this.v.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[1]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 7:this.m[0]=a,Y(this,this.C.frequency,a,c,d)}}};
self.le=class extends Z{constructor(b,a,c,d,e,f){super(b);this.T="distortion";this.m=[a,c,d,e,f];this.v=X(this);this.fc=X(this);this.ec=X(this);b=d;.01>b&&(b=.01);this.fc.gain.value=b;this.ec.gain.value=Math.pow(1/b,.6)*e;this.i=X(this);this.i.gain.value=f;this.h=X(this);this.h.gain.value=1-f;this.jc=this.g.createWaveShaper();this.Ic=new Float32Array(65536);for(e=0;32768>e;++e)f=e/32768,b=1.05*c*a-a,d=0>f?-f:f,d<a?b=d:(d=1-Math.exp(-(1/b)*(d-a)),b=a+b*d),f=b*(0>f?-1:1),this.Ic[32768+e]=f,this.Ic[32768-
e-1]=-f;this.jc.curve=this.Ic;this.v.connect(this.fc);this.v.connect(this.h);this.fc.connect(this.jc);this.jc.connect(this.ec);this.ec.connect(this.i)}j(){this.v.disconnect();this.fc.disconnect();this.jc.disconnect();this.ec.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.m[4]=a,Y(this,this.i.gain,a,c,d),Y(this,this.h.gain,
1-a,c,d)}}};self.ie=class extends Z{constructor(b,a,c,d,e,f){super(b);this.T="compressor";this.m=[a,c,d,e,f];this.l=this.g.createDynamicsCompressor();this.l.threshold.value=a;this.l.knee.value=c;this.l.ratio.value=d;this.l.attack.value=e;this.l.release.value=f}j(){this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(){}};
self.he=class extends Z{constructor(b,a,c){super(b);this.T="analyser";this.m=[a,c];this.l=this.g.createAnalyser();this.l.fftSize=a;this.l.smoothingTimeConstant=c;this.Md=new Float32Array(this.l.frequencyBinCount);this.ae=new Uint8Array(a);this.Zd=this.Ya=0;b=this.u;b.Pa.add(this);T(b)}j(){this.u.Pa.delete(this);this.l.disconnect();super.j()}Na(){this.l.getFloatFrequencyData(this.Md);this.l.getByteTimeDomainData(this.ae);const b=this.l.fftSize;let a=this.Ya=0;for(var c=0;c<b;++c){let d=(this.ae[c]-
128)/128;0>d&&(d=-d);this.Ya<d&&(this.Ya=d);a+=d*d}c=self.eb.De;this.Ya=c(this.Ya);this.Zd=c(Math.sqrt(a/b))}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(){}};
